---
layout: post
title: "ES6 Promise"
featured-img: promise
categories: [ES6, Javascript]
date: 2020-02-24 14:00
---

# ES6 Promise

Promise는 비동기 상태를 값으로 다룰 수 있는 객체 입니다.
<br>
Promise를 사용하면, 비동기 프로그래밍을 할 때 동기 프로그래밍 방식으로 코드를 작성할 수 있는데
<br>
프로미스가 나오기 전에는 콜백 패턴으로 많이 쓰였고, ES6에 프로미스가 포함되면서

널리 사용되고 있습니다.

## 콜백패턴의 문제

프로미스가 나오기 이전에는 콜백 패턴을 많이 사용 했었지만, 콜백이 조금만 중첩되도

코드가 상당히 복잡해지는 단점이 있었습니다.

```javascript
/* CallBack Pattern Example */
function requestData1(callback) {
    //...
    callback(data);
}

function requestData2(callback) {
    //...
    callback(data);
}

function onSuccess1(data) {
    console.log(data);
    requestData2(onSuccess2);
}

function onSuccess2(data) {
    console.log(data);
    //...
}

requestData1(onSuccess1);
```

위와 같이, 코드의 흐름이 순차적이지 않아서 코드를 읽기가 매우 불편 합니다.
<br>
Promise를 사용하면 코드를 순차적으로 실행되게 작성할 수 있습니다.

Promise로 코드를 작성하기 전에, 세가지 상태를 알아 봅시다.

***

## Promise의 세가지 상태

프로미스는 3가지의 상태가 있습니다.

* 대기(pending): 결과를 기다리는중
* 이행됨(fulfilled): 수행이 정상적으로 끝나서 결과값을 가지고 있음
* 거부됨(rejected): 수행이 비정상적으로 끝났음

여기서 이행됨, 거부됨 상태를 처리됨(settled) 상태라고 부릅니다.

## Promise를 생성하는 방법

프로미스는 다음 세가지 방식으로 생성할 수 있습니다.

```javascript
const p1 = new Promise((resolve, reject) => {
    //...
    resolve(data);
    //or reject('error msg');
});

const p2 = Promise.reject('error msg');
const p3 = Promise.resolve(param);
```

일반적인 방법은 p1과 같이 new 키워드를 사용해서 생성합니다.
<br>
이 방법으로 생성된 프로미스는 대기(pending) 상태가 되며, 생성자에 입력되는 함수는

resolve와 reject라는 콜백 함수를 매개 변수로 갖습니다.

1. 비동기로 어떤 작업을 수행성공했을때 resolve를 호출합니다.
2. 실패했을때 reject를 호출합니다.

* resolve: 이행됨
* reject: 거부됨 

p2와 같이 new 키워드를 사용하지 않고 reject를 호출하면, 거부됨 상태인 프로미스가 생성됩니다.

p3과 같이 resolve를 호출해도 프로미스가 생성되며, 입력값이 프로미스 였다면,
<br>
그 객체가 그대로 반환 되고, 프로미스가 아니라면 이행됨 상태인 프로미스가 반환됩니다.

***

## then 이용하기

then은 처리됨 상태가 된 프로미스를 처리할 때 사용되는 메소드 입니다.
<br>
프로미스가 처리됨 상태가 되면 then 메소드의 인수로 전달된 함수가 호출 됩니다.

```javascript
requestData().then(onResolve, onReject);
Promise.resolve(123).then(data => console.log(data)); // 123
Promise.reject('err').then(null, error => console.log(error)); // 에러 발생!!
```

프로미스가 처리됨 상태가 되면 onResolve 함수가 호출되고
<br>
거부됨 상태가 되면 onReject 함수가 호출 됩니다.

then 메소드는 항상 프로미스를 반환하며,
<br>
하나의 프로미스로부터 연속적으로 then 메소드를 호출 할 수 있습니다.

```javascript
/* 연속해서 then 메소드 호출하기 */
requestData1()
    .then(data => {
        console.log(data);
        return requestData2();
    })
    .then(data => {
        return data + 1;
    })
    .then(data => {
        throw new Error('some error');
    })
    .then(null, error => {
        console.log(error);
    });
```

onResolve 또는 onReject 함수에서 프로미스를 반환하면, 
<br>
then 메소드는 그 값을 그대로 반환하며, 프로미스가 아닌 값을 반환하면

then메소드는 이행됨 상태인 프로미스를 반환합니다.

onResolve 또는 onReject 함수 내부에서 예외가 발생하면 then 메소드는 거부됨 상태인 프로미스를 반환합니다.

결과적으로 ※ then 메소드는 항상 프로미스를 반환 합니다.

또한 then메소드의 가장 중요한 특징은, 항상 체이닝 된 순서대로 호출 된다는 점입니다.
<br>
이 특징때문에 비동기 프로그래밍을 할 때, 동기프로그래밍 방식으로 코드를 작성할 수 있습니다.


***

## catch

catch는 프로미스 수행 중 발생한 예외를 처리하는 메소드 입니다.
<br>
catch 메소드는 then 메소드의 onReject 함수와 같은 역할을 합니다.

then메소드의 onResolve 함수에서 발생한 예외는
<br> 
같은 then 메소드의 onReject 함수에서 처리되지 않습니다.

```javascript
/* then 메소드의 onReject를 사용했을 때의 문제점 */
Promise.resolve().then(
    () => {
        throw new Error('some error');
    },
    error => {
        console.log(error);
    }
);
```

프로미스에서 예외 처리할때는 then 메소드의 onReject 함수보다는 좀 더 직관적인

catch 메소드를 이용해야 합니다. 또한, catch 메소드 이후에도 then 메소드를 사용할 수 있습니다.

```javascript
/* onReject 함수를 사용하지 않고 catch를 사용한 예 */
Promise.resolve()
    .then(() => {
        throw new Error('some error');
    })
    .catch(error => {
        console.log(error);
    });

/* catch 메소드 이후에 then 메소드 사용하기 */
Promise.reject(10)
    .then(data => {
        console.log('then1:', data);
        return 20;
    })
    .catch(error => {
        console.log('catch: ', error);
        return 30;
    })
    .then(data => {
        console.log('then2: ', data);
    });
    //catch: 10
    //then2: 30
```

***

## Promise.all()로 병렬 처리하기

Promise.all은 여러 개의 프로미스를 병렬로 처리할때 사용하는 함수입니다.

then 메소드를 체이닝 하면 각각의 비동기 처리가 병렬로 처리되지 않고
<br>
순차적으로 실행됩니다.

※ 비동기 함수간에 서로 의존성이 없다면, 병렬로 처리 하는 것이 훨씬 빠르기 때문에,
<br>
다음과 같이 비동기 함수를 각각 호출하면 병렬로 처리 됩니다.

```javascript
requestData1().then(data => console.log(data));
requestData2().then(data => console.log(data));
```

위와 같이 여러 프로미스를 병렬로 처리하고 싶을 경우에 Promise.all을 사용합니다.

```javascript
Promise.all([requestData1(), requestData2()]).then(([data1, data2]) => {
    console.log(data1, data2);
});
```

Promise.all 함수는 프로미스를 반환하며, 모든 프로미스가 '처리됨' 상태가 되어야

최종적으로 '처리됨' 상태가 됩니다.

## 실습 해보기

간단하게 jsonplaceholder에 dummy json을 요청해보고,

then과 catch를 사용 해보는 실습입니다.

나중에 포스팅할 fetch API를 배우면 xhr을 사용할 필요가 없긴 한데,
<br>
아직 포스팅하지 않았기에 XMLHttpRequest를 사용 하였습니다.

```javascript
function asyncFunc() {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1");
        xhr.onload = () => resolve(xhr.responseText);
        xhr.onerror = () => reject(xhr.statusText);
        xhr.send();
    });
}

asyncFunc().then(json => {
    console.log(json);
    return json.length;
}).then(jsonLength => {
    console.log(`Length: ${jsonLength}`);
    throw new Error("error test");
}).catch(error => {
    console.log(error);
});
```

***

여기까지 Promise에 대해 알아보았는데, 잠깐 숙지 할점을 정리 하자면,

* then 메소드 내부 함수에서 return 키워드를 꼭 작성하기(작성하지 않으면 undefined)
* Promise는 불변 객체라는 것. (then메소드는 기존 객체를 수정하지 않고 새롭게 반환)
* Promise를 중첩해서 사용하지 않기
* 예외 처리 신경쓰기

여기 까지 입니다!!

추후 포스팅에서는 향상된 비동기 프로그래밍 Async/Await에 대해 알아봅시다.


